# Generated by Django 5.1 on 2024-08-29 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('campos', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='usuario/')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.instituicao')),
                ('instrumento', models.ManyToManyField(to='Perfil.instrumento')),
            ],
        ),
    ]
